/*DROP TABLE t_psd_quarto CASCADE CONSTRAINTS;
DROP SEQUENCE SQ_T_PSD_QUARTO;
DROP TABLE t_psd_reserva CASCADE CONSTRAINTS;
DROP SEQUENCE SQ_T_PSD_RESERVA;*/

CREATE TABLE t_psd_quarto (
    nr_quarto       NUMBER(2) NOT NULL PRIMARY KEY,
    nr_max_pessoas  NUMBER(1) NOT NULL,
    vl_diaria       NUMBER(6, 2) NOT NULL
);
CREATE SEQUENCE SQ_T_PSD_QUARTO INCREMENT BY 2 START WITH 2 NOCYCLE ORDER;

CREATE TABLE t_psd_reserva (
    id_reserva  NUMBER(8) NOT NULL PRIMARY KEY,
    nr_quarto   NUMBER(2) NOT NULL,
    dt_entrada  DATE NOT NULL,
    dt_saida    DATE NOT NULL,
    nr_pessoas  NUMBER(1) NOT NULL
);
CREATE SEQUENCE SQ_T_PSD_RESERVA INCREMENT BY 1 START WITH 1 NOCYCLE ORDER;


SELECT * FROM T_PSD_QUARTO;
SELECT * FROM T_PSD_RESERVA;