DROP TABLE TB_ALUNO;
DROP SEQUENCE SQ_ALUNO;

CREATE TABLE TB_ALUNO (
	ID NUMBER NOT NULL PRIMARY KEY,
	RM NUMBER NOT NULL UNIQUE,
	NOME VARCHAR2(100) NOT NULL,
	ATIVO NUMBER(1) DEFAULT 0,
	NOTA1 DECIMAL(3,1) DEFAULT 0,
	NOTA2 DECIMAL(3,1) DEFAULT 0
);

CREATE SEQUENCE SQ_ALUNO INCREMENT BY 1 START WITH 1 NOCYCLE ORDER;

SELECT * FROM TB_ALUNO;