CREATE TABLE TB_RESERVA (
 ID_RESERVA NUMBER NOT NULL PRIMARY KEY,
 NM_CLIENTE VARCHAR2(60) NOT NULL,
 DT_ENTRADA DATE NOT NULL,
 DT_SAIDA DATE NOT NULL,
 NR_QUARTO NUMBER(2) NOT NULL,
 NR_PESSOAS NUMBER(1) NOT NULL,
 DS_QUARTO VARCHAR2(12) NOT NULL
);

CREATE SEQUENCE SQ_RESERVA INCREMENT BY 1 START WITH 1 NOCYCLE ORDER;